# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataReader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import subprocess
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor,QIcon
from PyQt5.QtWidgets import QFileDialog,QMessageBox
import numpy as np
import scipy.io as scio
import pyedflib
import ctypes
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 540)
        MainWindow.setMinimumSize(QtCore.QSize(886, 544))
        MainWindow.setMaximumSize(QtCore.QSize(886, 544))
        MainWindow.setWindowIcon(QIcon("./QL_logo.ico"))
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 700, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.DeviceConnection = QtWidgets.QPushButton(self.centralwidget)
        self.DeviceConnection.setGeometry(QtCore.QRect(40, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.DeviceConnection.setFont(font)
        self.DeviceConnection.setObjectName("DeviceConnection")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(150, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 70, 48, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Vcheck = QtWidgets.QPushButton(self.centralwidget)
        self.Vcheck.setGeometry(QtCore.QRect(40, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.Vcheck.setFont(font)
        self.Vcheck.setObjectName("Vcheck")
        self.VtotalBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.VtotalBox.setGeometry(QtCore.QRect(180, 180, 81, 31))
        self.VtotalBox.setObjectName("VtotalBox")
        self.Vtotal = QtWidgets.QLabel(self.centralwidget)
        self.Vtotal.setGeometry(QtCore.QRect(200, 160, 48, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.Vtotal.setFont(font)
        self.Vtotal.setAlignment(QtCore.Qt.AlignCenter)
        self.Vtotal.setObjectName("Vtotal")
        self.VremainBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.VremainBox.setGeometry(QtCore.QRect(320, 180, 81, 31))
        self.VremainBox.setObjectName("VremainBox")
        self.Vremain = QtWidgets.QLabel(self.centralwidget)
        self.Vremain.setGeometry(QtCore.QRect(320, 160, 81, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.Vremain.setFont(font)
        self.Vremain.setAlignment(QtCore.Qt.AlignCenter)
        self.Vremain.setObjectName("Vremain")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(460, 90, 391, 341))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.DeviceConnection_3 = QtWidgets.QPushButton(self.centralwidget)
        self.DeviceConnection_3.setGeometry(QtCore.QRect(490, 450, 331, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.DeviceConnection_3.setFont(font)
        self.DeviceConnection_3.setObjectName("DeviceConnection_3")
        self.Vremain_2 = QtWidgets.QLabel(self.centralwidget)
        self.Vremain_2.setGeometry(QtCore.QRect(600, 70, 120, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.Vremain_2.setFont(font)
        self.Vremain_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Vremain_2.setObjectName("Vremain_2")
        self.datapath_label = QtWidgets.QLabel(self.centralwidget)
        self.datapath_label.setGeometry(QtCore.QRect(170, 250, 111, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.datapath_label.setFont(font)
        self.datapath_label.setAlignment(QtCore.Qt.AlignCenter)
        self.datapath_label.setObjectName("datapath_label")
        self.data_export_button = QtWidgets.QPushButton(self.centralwidget)
        self.data_export_button.setGeometry(QtCore.QRect(40, 330, 100, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.data_export_button.setFont(font)
        self.data_export_button.setObjectName("data_export_button")
        self.data_clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.data_clear_button.setGeometry(QtCore.QRect(260, 330, 140, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.data_clear_button.setFont(font)
        self.data_clear_button.setObjectName("data_clear_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 510, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 510, 180, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.path_button = QtWidgets.QPushButton(self.centralwidget)
        self.path_button.setGeometry(QtCore.QRect(360, 280, 40, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.path_button.setFont(font)
        self.path_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.path_button.setObjectName("path_button")
        self.data_path_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.data_path_box.setGeometry(QtCore.QRect(40, 280, 360, 30))
        self.data_path_box.setObjectName("data_path_box")
        self.data_path_box_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.data_path_box_2.setGeometry(QtCore.QRect(40, 420, 360, 30))
        self.data_path_box_2.setObjectName("data_path_box_2")
        self.data_translate_button = QtWidgets.QPushButton(self.centralwidget)
        self.data_translate_button.setGeometry(QtCore.QRect(40, 460, 160, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.data_translate_button.setFont(font)
        self.data_translate_button.setObjectName("data_translate_button")
        self.data_path_data = QtWidgets.QPushButton(self.centralwidget)
        self.data_path_data.setGeometry(QtCore.QRect(360, 420, 40, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_path_data.setFont(font)
        self.data_path_data.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.data_path_data.setObjectName("data_path_data")
        self.datapath_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.datapath_label_2.setGeometry(QtCore.QRect(130, 390, 181, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.datapath_label_2.setFont(font)
        self.datapath_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.datapath_label_2.setObjectName("datapath_label_2")
        self.data_translate_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.data_translate_button_2.setGeometry(QtCore.QRect(240, 460, 160, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.data_translate_button_2.setFont(font)
        self.data_translate_button_2.setObjectName("data_translate_button_2")



        self.label.raise_()
        self.DeviceConnection.raise_()
        self.textBrowser.raise_()
        self.label_2.raise_()
        self.Vcheck.raise_()
        self.VtotalBox.raise_()
        self.Vtotal.raise_()
        self.VremainBox.raise_()
        self.Vremain.raise_()
        self.textBrowser_2.raise_()
        self.DeviceConnection_3.raise_()
        self.Vremain_2.raise_()
        self.datapath_label.raise_()
        self.data_export_button.raise_()
        self.data_clear_button.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.data_path_box.raise_()
        self.path_button.raise_()
        self.data_path_box_2.raise_()
        self.data_translate_button.raise_()
        self.data_path_data.raise_()
        self.datapath_label_2.raise_()
        self.data_translate_button_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.DeviceConnection.clicked.connect(self.device_connect)
        self.Vcheck.clicked.connect(self.Volume_Check)
        self.data_export_button.clicked.connect(self.data_export)
        self.data_clear_button.clicked.connect(self.data_clear)
        self.DeviceConnection_3.clicked.connect(self.data_check)
        self.path_button.clicked.connect(self.path_choose)
        self.data_path_data.clicked.connect(self.data_choose)
        self.data_translate_button.clicked.connect(self.data_translate_mat)


        # self.data_translate_button_2.clicked.connect(self.data_translate_edf)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "QL可穿戴式睡眠脑电记录设备数据管理软件"))
        self.DeviceConnection.setText(_translate("MainWindow", "连接设备"))
        self.label_2.setText(_translate("MainWindow", "设备ID"))
        self.Vcheck.setText(_translate("MainWindow", "查询容量"))
        self.Vtotal.setText(_translate("MainWindow", "总容量"))
        self.Vremain.setText(_translate("MainWindow", "剩余容量"))
        self.DeviceConnection_3.setText(_translate("MainWindow", "查询数据"))
        self.Vremain_2.setText(_translate("MainWindow", "数据列表"))
        self.datapath_label.setText(_translate("MainWindow", "数据导出地址"))
        self.data_export_button.setText(_translate("MainWindow", "数据导出"))
        self.data_clear_button.setText(_translate("MainWindow", "清除数据"))
        self.label_3.setText(_translate("MainWindow", "copyright©"))
        self.label_4.setText(_translate("MainWindow", "全澜科技有限公司出品"))
        self.path_button.setText(_translate("MainWindow", "..."))
        self.data_translate_button.setText(_translate("MainWindow", "转换为.mat格式"))
        self.data_path_data.setText(_translate("MainWindow", "..."))
        self.datapath_label_2.setText(_translate("MainWindow", "数据转换"))
        # self.data_translate_button_2.setText(_translate("MainWindow", "转换为.edf格式"))
        # self.batch_translate_mat_2.setText(_translate("MainWindow", "转换为.edf格式"))
        self.batch_translate_mat.setText(_translate("MainWindow", "转换为.mat格式"))
        self.batch_translate_label.setText(_translate("MainWindow", "批量转换"))
        self.batch_translate_buttom.setText(_translate("MainWindow", "..."))


    def device_connect(self):
        cmd = 'adb devices'  # list devices
        d = os.popen(cmd)
        # d = os.system(cmd)
        #time.sleep(1)
        f = d.read()
        # p = subprocess.Popen(['adb', 'devices'], shell=True,stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        # p.wait(1)
        # f = p.stdout.read().decode('gbk')
        # def no_path_warning(self):
        #
        #     no_path_warning = QMessageBox.information(None, "Error", "请确认设备已连接且adb驱动已安装")
        #
        #     return no_path_warning
        #
        # if f == '':
        #     A = no_path_warning(self)
        #     return
        # else:
        begin = f.find('\n')
        end = f.rfind('\t')
        global device
        device = f[begin + 1:end]  # get device ID
        self.textBrowser.setText(device)



    def Volume_Check(self):
        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请连接设备")

            return no_path_warning

        try:
            device
        except NameError:
            A = no_path_warning(self)
            return
        else:
            cmd = 'adb shell df -h'
            d = os.popen(cmd)
            f = d.read()
            # tot = f.find('3.0G')
            tot = 202
            # ava = f.find('261M')
            ava = 213
            comp_tot = f[tot:tot + 5]
            comp_ava = f[ava:ava + 5]
            self.VtotalBox.setText(comp_tot)
            self.VremainBox.setText(comp_ava)

    def data_check(self):
        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请点击连接设备")

            return no_path_warning

        try:
            device
        except NameError:
            A = no_path_warning(self)
            return
        else:
            cmd = 'adb -s ' + str(device) + ' shell "ls -a /userdata/box/data"'
            d = os.popen(cmd)
            f = d.read()
            self.textBrowser_2.setText(f)

    def path_choose(self):
        global path
        path = QFileDialog.getExistingDirectory(None,
                  "选取指定文件夹")
        self.data_path_box.setText(str(path))


    def data_choose(self):
        global path_of_data
        path_of_data = QFileDialog.getOpenFileName(None,
                  "选取指定文件")
        self.data_path_box_2.setText(str(path_of_data))


    def data_choose_batch(self):
        global path_of_data_batch
        path_of_data_batch = QFileDialog.getExistingDirectory(None,
                  "选取指定文件夹")
        self.data_path_box_2.setText(str(path_of_data_batch))








    def DataloaderX7(self,path, signed=False):  # for ACC-36727, the sign is False
        DataTotal = []
        PackageIDs = []
        with open(path, 'rb') as f:
            TotalLen = len(f.read())
            f.seek(0, 0)
            DataType = f.read(3)
            f.seek(12, 0)
            PackageCount = int.from_bytes(f.read(4), byteorder='little', signed=False)
            f.seek(16, 0)
            Resolution = int.from_bytes(f.read(1), byteorder='little', signed=False)

            f.seek(21, 0)
            SampleRate = int.from_bytes(f.read(4), byteorder='little', signed=False)
            f.seek(81, 0)
            ChannelDataLenth = int.from_bytes(f.read(4), byteorder='little', signed=False)

            f.seek(30, 0)
            ST_Y = int.from_bytes(f.read(2), byteorder='little', signed=False)
            ST_M = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ST_D = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ST_H = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ST_Min = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ST_S = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ST_ms = int.from_bytes(f.read(2), byteorder='little', signed=False)

            f.seek(40, 0)
            ET_Y = int.from_bytes(f.read(2), byteorder='little', signed=False)
            ET_M = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ET_D = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ET_H = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ET_Min = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ET_S = int.from_bytes(f.read(1), byteorder='little', signed=False)
            ET_ms = int.from_bytes(f.read(2), byteorder='little', signed=False)

            ST = np.array([ST_Y, ST_M, ST_D, ST_H, ST_Min, ST_S, ST_ms])
            ET = np.array([ET_Y, ET_M, ET_D, ET_H, ET_Min, ET_S, ET_ms])
            # package_sent= (ET - ST)*np.array([365*24*60*60*1000,30*24*60*60*1000,24*60*60*1000,60*60*1000,60*1000,1000,0])/100 # 100 means package send frequency
            # package_loss = PacketCount/sum(package_sent)*100

            f.seek(90, 0)
            DataOffSet = int.from_bytes(f.read(4), byteorder='little', signed=signed)
            PackageOffSet = 8


            if DataType == b'EEG':
                PackageDataLength = 208

            elif DataType == b'ACC':
                PackageDataLength = 38

            elif DataType == b'sti':
                PackageDataLength = 12

            elif DataType == b'EMG':
                PackageDataLength = 248

            if not PackageCount:
                PackageCount = int((TotalLen - DataOffSet) / PackageDataLength)
            else:
                PackageDataLength = int((TotalLen - DataOffSet) / PackageCount)


            f.seek(DataOffSet, 0)
            for i in range(PackageCount):
                PackageT = f.read(PackageDataLength)

                PackageID = int.from_bytes(PackageT[0:8], byteorder='little', signed=signed)
                PackageT = PackageT[8:]
                for j in range(int(len(PackageT) // Resolution)):
                    # print(int(len(PackageT) // 2))
                    DataT = int.from_bytes(PackageT[j * Resolution:j * Resolution + Resolution], byteorder='little',
                                           signed=signed)
                    DataTotal.append(DataT)
                    # print(j)
                PackageIDs.append(PackageID)
            PackageIDs = np.array(PackageIDs)

            if str(DataType, encoding="utf-8") == 'EEG':
                DataTotal = np.array(DataTotal)
                A = DataTotal
                DataTotal = DataTotal[0:len(DataTotal) // 2 * 2]
                DataTotal_T = DataTotal.reshape(-1, 2)
                DataTotal = []
                DataTotal.append(DataTotal_T[:, 0])
                DataTotal.append(DataTotal_T[:, 1])

            elif str(DataType, encoding="utf-8") == 'ACC':
                DataTotal = np.array(DataTotal)
                A = DataTotal
                DataTotal = DataTotal[0:len(DataTotal) // 3 * 3]
                DataTotal_T = DataTotal.reshape(-1, 3)
                DataTotal = []
                DataTotal.append(DataTotal_T[:, 0])
                DataTotal.append(DataTotal_T[:, 1])
                DataTotal.append(DataTotal_T[:, 2])

            elif str(DataType, encoding="utf-8") == 'EMG':
                DataTotal = np.array(DataTotal)
                DataTotal = DataTotal[0:len(DataTotal) // 8 * 8]
                DataTotal_T = DataTotal.reshape(-1, 8)
                DataTotal = []
                DataTotal.append(DataTotal_T[:, 0])
                DataTotal.append(DataTotal_T[:, 1])
                DataTotal.append(DataTotal_T[:, 2])
                DataTotal.append(DataTotal_T[:, 3])
                DataTotal.append(DataTotal_T[:, 4])
                DataTotal.append(DataTotal_T[:, 5])
                DataTotal.append(DataTotal_T[:, 6])
                DataTotal.append(DataTotal_T[:, 7])

            # package_loss = (sum(PackageIDs[2:-1] - PackageIDs[1:-2] - 100) / 100) / (
            #             sum(PackageIDs[2:-1] - PackageIDs[1:-2] - 100) / 100 + PackageCount)

            package_loss = (sum(PackageIDs[2:-1] - PackageIDs[1:-2] - 100) / 100) / (
                        sum(PackageIDs[2:-1] - PackageIDs[1:-2] - 100) / 100 + PackageCount)

        return DataTotal, PackageIDs, SampleRate, ST, ET, package_loss

    # def DataParseBatch(self, path_of_data_batch):
    #
    #     for file_name in os.listdir(path_of_data_batch):
    #




# self.DataloaderX7()




    def data_translate_mat(self):

        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请选择导出路径")

            return no_path_warning
        try:
            path_of_data
        except NameError:
            A = no_path_warning(self)
            return
        else:
            data_p = path_of_data[0]
            print(data_p[-3::])

            EEG_p = data_p

        if EEG_p[-3::] == 'eeg':
            EEG, PackageIDs, SampleRate, ST, ET, package_loss = np.array(self.DataloaderX7(EEG_p, signed=False))

            scio.savemat(EEG_p[:-3] + "mat", {'EEG': EEG, 'PackageIDs': PackageIDs, 'SampleRate': SampleRate,
                                              'StartTime': ST, 'EndTime': ET, 'package_loss': package_loss})
        elif EEG_p[-3::] == 'acc':
            ACC_p = EEG_p
            ACC_T, PackageIDs, SampleRate, ST, ET, package_loss = self.DataloaderX7(ACC_p, signed=False)
            # plt.plot(ACC_T)
            ACC_T = ACC_T
            ACCx_raw = ACC_T[0]- 32767
            ACCy_raw = ACC_T[1]- 32767
            ACCz_raw = ACC_T[2]- 32767

            ACCx = ACC_T[0][1:-2] - ACC_T[0][2:-1]
            ACCy = ACC_T[1][1:-2] - ACC_T[1][2:-1]
            ACCz = ACC_T[2][1:-2] - ACC_T[2][2:-1]
            ACC = np.abs(ACCx) + np.abs(ACCy) + np.abs(ACCz)

            scio.savemat(EEG_p[:-3] + "mat",
                         {'ACC': ACC, 'ACCT': ACC_T, 'ACCx_raw': ACCx_raw, 'ACCy_raw': ACCy_raw, 'ACCz_raw': ACCz_raw,
                          'ACCx': ACCx, 'ACCy': ACCy, 'ACCz': ACCz, 'PackageIDs': PackageIDs, 'SampleRate': SampleRate,
                          'StartTime': ST, 'EndTime': ET, 'package_loss': package_loss})


        elif EEG_p[-3::] == 'emg':
            EMG_p = EEG_p
            EMG, PackageIDs, SampleRate, ST, ET, package_loss = self.DataloaderX7(EMG_p, signed=False)
            scio.savemat(EEG_p[:-3] + "mat", {'EMG': EMG, 'PackageIDs': PackageIDs, 'SampleRate': SampleRate,
                                              'StartTime': ST, 'EndTime': ET, 'package_loss': package_loss})

        elif EEG_p[-3::] == 'sti':
            Sti_p = EEG_p
            Sti_T, PackageIDs, SampleRate, ST, ET, package_loss = self.DataloaderX7(Sti_p, signed=False)
            # plt.plot(ACC_T)
            # ACCx=ACC_T[0][1:-2] - ACC_T[0][2:-1]
            # ACCy = ACC_T[1][1:-2] - ACC_T[1][2:-1]
            # ACCz = ACC_T[2][1:-2] - ACC_T[2][2:-1]
            # ACC = np.abs(ACCx) + np.abs(ACCy) + np.abs(ACCz)

            scio.savemat(EEG_p[:-3] + "mat", {'StiIdx': Sti_T})

        export_finish = QMessageBox.information(None, "提示", "数据转换完成，请查看原文件夹")
        # start_directory = path
        # os.startfile(start_directory)













    def write_edf(self, file, n_channel, datatype, data_and_info):
        f = pyedflib.EdfWriter(file,
                               n_channel,
                               file_type=pyedflib.FILETYPE_EDFPLUS)
        channel_info = []
        data_list = []
        dimension = '1'
        physical_max = 32765
        physical_min = -32765
        digital_max = 32765
        # sf = 20

        if datatype == 'eeg':
            dimension = 'uV'
            # physical_max = 32767
            # digital_max = 32767
            data_and_info[0]=(data_and_info[0] - 43439)* 2.5/65535 * 1000 * 1000 / 100
            sf = data_and_info[3] + 500
        elif datatype == 'acc':
            dimension = '1'
            # physical_max = 32767
            # digital_max = 32767
            data_and_info[0]=data_and_info[0]
            sf = 50

        ch_dict = {
            'label': datatype,
            'dimension': dimension,
            'sample_rate': sf,
            'physical_max': physical_max,
            'physical_min': physical_min,
            'digital_max': digital_max,
            'digital_min': -32765,
            'start_time': data_and_info[1],
            'end_time': data_and_info[2]
        }

        channel_info.append(ch_dict)
        data_list.append(data_and_info[0])

        f.setSignalHeaders(channel_info)
        f.writeSamples(data_list)
        f.close()

        export_finish = QMessageBox.information(None, "提示", "数据转换完成，请查看原文件夹")
        # start_directory = path
        # os.startfile(start_directory)

    def data_translate_edf(self):
        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请选择导出路径")

            return no_path_warning
        try:
            path_of_data
        except NameError:
            A = no_path_warning(self)
            return
        else:
            data_p = path_of_data[0]
            print(data_p[-3::])


        if data_p[-3::] == 'eeg':
            data_and_info = self.DataloaderX6(data_p, signed=False)
            export_path =data_p[:-4]+'.edf'

            self.write_edf(export_path,1, 'eeg', data_and_info)
        elif data_p[-3::] == 'acc':
            data_and_info=self.DataloaderX6(data_p, signed=True)
            # print(len(data_and_info[0]) // 20 )
            if len(data_and_info[0])%3 !=0:
                data_and_info[0] = data_and_info[0][:len(data_and_info[0])//3*3]

            # print(len(data_and_info[0]))
            # print(data_p[:-4] + "ACC.mat")

            ACCx = np.array(data_and_info[0]).reshape(-1, 3)[1:, 0] - np.array(
                data_and_info[0]).reshape(-1, 3)[0:-1, 0]
            ACCy = np.array(data_and_info[0]).reshape(-1, 3)[1:, 1] - np.array(
                data_and_info[0]).reshape(-1, 3)[0:-1, 1]
            ACCz = np.array(data_and_info[0]).reshape(-1, 3)[1:, 2] - np.array(
                data_and_info[0]).reshape(-1, 3)[0:-1, 2]
            ACC = np.abs(ACCx) + np.abs(ACCy) + np.abs(ACCz)
            data_and_info[0] = ACC[:len(ACC)//20*20]
            # SF = np.array(data_and_info[3])

            export_path = data_p[:-4] + '.edf'
            self.write_edf(export_path, 1, 'acc', data_and_info)



    def data_export(self):
        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "连接设备，并选择导出路径")

            return no_path_warning
        try:
            device or path
        except NameError:
            A = no_path_warning(self)
            return
        try:
            path
        except NameError:
            A = no_path_warning(self)
            return
        else:
            # if path ==None:
            #     no_path_warning = QMessageBox.information(None, "提示", "请选择导出路径")
            #     return

            cmd = 'adb -s ' + str(device) + ' pull /userdata/box/data ' + path
            os.popen(cmd)
            cmd = 'adb -s ' + str(device) + ' pull /userdata/box/head.log ' + path
            os.popen(cmd)
            cmd = 'adb -s ' + str(device) + ' pull /userdata/box/box.log ' + path
            os.popen(cmd)
            export_finish = QMessageBox.information(None, "提示", "数据导出完成，请查看导出的文件夹")
            start_directory = path
            os.startfile(start_directory)



    def data_clear(self):

        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请连接设备")

            return no_path_warning
        try:
            device
        except NameError:
            A = no_path_warning(self)
            return
        else:
            cmd = f'adb -s {str(device)} shell rm -rf /userdata/box/data/*'
            os.popen(cmd)
            export_finish = QMessageBox.information(None, "提示", "数据删除完成")


