# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataReader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import subprocess
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor,QIcon
from PyQt5.QtWidgets import QFileDialog,QMessageBox
import numpy as np
import scipy.io as scio
import pyedflib
import ctypes
from data2mat import data_translate_mat
from transdata2edf import data_translate_edf, data_translate_edf_path, edf_join
def find_file(root, func, find_dir = False,  recursion = True):
    ret = []
    for f in os.listdir(root):
        full_name = root + '/' + f
        if(os.path.isfile(full_name)):
            if func(full_name):
                ret.append(full_name)
        else:
            if find_dir:
               if func(full_name):
                    ret.append(full_name)
            if recursion:
                ret += find_file(full_name, func, find_dir, recursion)
    return ret

def is_dir_all_file(root):
    for f in os.listdir(root):
        full_name = root + '/' + f
        if(os.path.isdir(full_name)):
            return False
    return True
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 544)
        MainWindow.setMinimumSize(QtCore.QSize(886, 544))
        MainWindow.setMaximumSize(QtCore.QSize(886, 544))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 514, 27))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.DeviceConnection = QtWidgets.QPushButton(self.centralwidget)
        self.DeviceConnection.setGeometry(QtCore.QRect(40, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.DeviceConnection.setFont(font)
        self.DeviceConnection.setObjectName("DeviceConnection")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(150, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 70, 48, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Vcheck = QtWidgets.QPushButton(self.centralwidget)
        self.Vcheck.setGeometry(QtCore.QRect(40, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.Vcheck.setFont(font)
        self.Vcheck.setObjectName("Vcheck")
        self.VtotalBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.VtotalBox.setGeometry(QtCore.QRect(180, 150, 81, 31))
        self.VtotalBox.setObjectName("VtotalBox")
        self.Vtotal = QtWidgets.QLabel(self.centralwidget)
        self.Vtotal.setGeometry(QtCore.QRect(200, 130, 48, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.Vtotal.setFont(font)
        self.Vtotal.setAlignment(QtCore.Qt.AlignCenter)
        self.Vtotal.setObjectName("Vtotal")
        self.VremainBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.VremainBox.setGeometry(QtCore.QRect(320, 150, 81, 31))
        self.VremainBox.setObjectName("VremainBox")
        self.Vremain = QtWidgets.QLabel(self.centralwidget)
        self.Vremain.setGeometry(QtCore.QRect(320, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.Vremain.setFont(font)
        self.Vremain.setAlignment(QtCore.Qt.AlignCenter)
        self.Vremain.setObjectName("Vremain")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(460, 90, 391, 341))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.DeviceConnection_3 = QtWidgets.QPushButton(self.centralwidget)
        self.DeviceConnection_3.setGeometry(QtCore.QRect(490, 450, 331, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.DeviceConnection_3.setFont(font)
        self.DeviceConnection_3.setObjectName("DeviceConnection_3")
        self.Vremain_2 = QtWidgets.QLabel(self.centralwidget)
        self.Vremain_2.setGeometry(QtCore.QRect(620, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.Vremain_2.setFont(font)
        self.Vremain_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Vremain_2.setObjectName("Vremain_2")
        self.datapath_label = QtWidgets.QLabel(self.centralwidget)
        self.datapath_label.setGeometry(QtCore.QRect(170, 190, 111, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.datapath_label.setFont(font)
        self.datapath_label.setAlignment(QtCore.Qt.AlignCenter)
        self.datapath_label.setObjectName("datapath_label")
        self.data_export_button = QtWidgets.QPushButton(self.centralwidget)
        self.data_export_button.setGeometry(QtCore.QRect(40, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.data_export_button.setFont(font)
        self.data_export_button.setObjectName("data_export_button")
        self.data_clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.data_clear_button.setGeometry(QtCore.QRect(300, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.data_clear_button.setFont(font)
        self.data_clear_button.setObjectName("data_clear_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 510, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 510, 180, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.path_button = QtWidgets.QPushButton(self.centralwidget)
        self.path_button.setGeometry(QtCore.QRect(360, 220, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.path_button.setFont(font)
        self.path_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.path_button.setObjectName("path_button")
        self.data_path_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.data_path_box.setGeometry(QtCore.QRect(40, 220, 361, 31))
        self.data_path_box.setObjectName("data_path_box")
        self.data_path_box_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.data_path_box_2.setGeometry(QtCore.QRect(40, 320, 361, 31))
        self.data_path_box_2.setObjectName("data_path_box_2")
        self.data_translate_button = QtWidgets.QPushButton(self.centralwidget)
        self.data_translate_button.setGeometry(QtCore.QRect(40, 360, 160, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.data_translate_button.setFont(font)
        self.data_translate_button.setObjectName("data_translate_button")
        self.data_path_data = QtWidgets.QPushButton(self.centralwidget)
        self.data_path_data.setGeometry(QtCore.QRect(360, 320, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_path_data.setFont(font)
        self.data_path_data.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.data_path_data.setObjectName("data_path_data")
        self.datapath_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.datapath_label_2.setGeometry(QtCore.QRect(130, 290, 181, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.datapath_label_2.setFont(font)
        self.datapath_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.datapath_label_2.setObjectName("datapath_label_2")
        self.data_translate_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.data_translate_button_2.setGeometry(QtCore.QRect(240, 360, 160, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.data_translate_button_2.setFont(font)
        self.data_translate_button_2.setObjectName("data_translate_button_2")
        self.batch_translate_mat_2 = QtWidgets.QPushButton(self.centralwidget)
        self.batch_translate_mat_2.setGeometry(QtCore.QRect(240, 470, 160, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.batch_translate_mat_2.setFont(font)
        self.batch_translate_mat_2.setObjectName("batch_translate_mat_2")
        self.batch_translate_mat = QtWidgets.QPushButton(self.centralwidget)
        self.batch_translate_mat.setGeometry(QtCore.QRect(40, 470, 160, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.batch_translate_mat.setFont(font)
        self.batch_translate_mat.setObjectName("batch_translate_mat")
        self.batch_translate_label = QtWidgets.QLabel(self.centralwidget)
        self.batch_translate_label.setGeometry(QtCore.QRect(130, 400, 181, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.batch_translate_label.setFont(font)
        self.batch_translate_label.setAlignment(QtCore.Qt.AlignCenter)
        self.batch_translate_label.setObjectName("batch_translate_label")
        self.batch_translate_button = QtWidgets.QPushButton(self.centralwidget)
        self.batch_translate_button.setGeometry(QtCore.QRect(360, 430, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.batch_translate_button.setFont(font)
        self.batch_translate_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.batch_translate_button.setObjectName("batch_translate_button")
        self.batch_translate_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.batch_translate_box.setGeometry(QtCore.QRect(40, 430, 361, 31))
        self.batch_translate_box.setObjectName("batch_translate_box")
        self.label.raise_()
        self.DeviceConnection.raise_()
        self.textBrowser.raise_()
        self.label_2.raise_()
        self.Vcheck.raise_()
        self.VtotalBox.raise_()
        self.Vtotal.raise_()
        self.VremainBox.raise_()
        self.Vremain.raise_()
        self.textBrowser_2.raise_()
        self.DeviceConnection_3.raise_()
        self.Vremain_2.raise_()
        self.datapath_label.raise_()
        self.data_export_button.raise_()
        self.data_clear_button.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.data_path_box.raise_()
        self.path_button.raise_()
        self.data_path_box_2.raise_()
        self.data_translate_button.raise_()
        self.data_path_data.raise_()
        self.datapath_label_2.raise_()
        self.data_translate_button_2.raise_()
        self.batch_translate_mat_2.raise_()
        self.batch_translate_mat.raise_()
        self.batch_translate_label.raise_()
        self.batch_translate_box.raise_()
        self.batch_translate_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.DeviceConnection.clicked.connect(self.device_connect) # type: ignore
        self.Vcheck.clicked.connect(self.Volume_Check) # type: ignore
        self.data_export_button.clicked.connect(self.data_export) # type: ignore
        self.data_clear_button.clicked.connect(self.data_clear) # type: ignore
        self.DeviceConnection_3.clicked.connect(self.data_check) # type: ignore
        self.path_button.clicked.connect(self.path_choose)
        self.data_path_data.clicked.connect(self.data_choose)
        self.data_translate_button.clicked.connect(self.data_sigle_translate_mat)
        self.batch_translate_button.clicked.connect(self.data_choose_batch)
        self.batch_translate_mat.clicked.connect(self.data_batch_translate_mat)

        self.batch_translate_mat_2.clicked.connect(self.data_batch_translate_edf)
        self.data_translate_button_2.clicked.connect(self.data_translate_edf)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "QL可穿戴式睡眠脑电记录设备数据管理软件"))
        self.DeviceConnection.setText(_translate("MainWindow", "连接设备"))
        self.label_2.setText(_translate("MainWindow", "设备ID"))
        self.Vcheck.setText(_translate("MainWindow", "查询容量"))
        self.Vtotal.setText(_translate("MainWindow", "总容量"))
        self.Vremain.setText(_translate("MainWindow", "剩余容量"))
        self.DeviceConnection_3.setText(_translate("MainWindow", "查询数据"))
        self.Vremain_2.setText(_translate("MainWindow", "数据列表"))
        self.datapath_label.setText(_translate("MainWindow", "数据导出地址"))
        self.data_export_button.setText(_translate("MainWindow", "数据导出"))
        self.data_clear_button.setText(_translate("MainWindow", "清除数据"))
        self.label_3.setText(_translate("MainWindow", "copyright©"))
        self.label_4.setText(_translate("MainWindow", "全澜科技有限公司出品"))
        self.path_button.setText(_translate("MainWindow", "..."))
        self.data_translate_button.setText(_translate("MainWindow", "转换为.mat格式"))
        self.data_path_data.setText(_translate("MainWindow", "..."))
        self.datapath_label_2.setText(_translate("MainWindow", "数据转换"))
        self.data_translate_button_2.setText(_translate("MainWindow", "转换为.edf格式"))
        self.batch_translate_mat_2.setText(_translate("MainWindow", "合并"))
        # self.batch_translate_mat.setText(_translate("MainWindow", "转换为.mat格式"))
        self.batch_translate_label.setText(_translate("MainWindow", "合并转换为edf格式"))
        self.batch_translate_button.setText(_translate("MainWindow", "..."))



    def device_connect(self):
        cmd = 'adb devices'  # list devices
        d = os.popen(cmd)
        # d = os.system(cmd)
        #time.sleep(1)
        f = d.read()
        # p = subprocess.Popen(['adb', 'devices'], shell=True,stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        # p.wait(1)
        # f = p.stdout.read().decode('gbk')
        # def no_path_warning(self):
        #
        #     no_path_warning = QMessageBox.information(None, "Error", "请确认设备已连接且adb驱动已安装")
        #
        #     return no_path_warning
        #
        # if f == '':
        #     A = no_path_warning(self)
        #     return
        # else:
        begin = f.find('\n')
        end = f.rfind('\t')
        global device
        device = f[begin + 1:end]  # get device ID
        self.textBrowser.setText(device)



    def Volume_Check(self):
        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请连接设备")

            return no_path_warning

        try:
            device
        except NameError:
            A = no_path_warning(self)
            return
        else:
            cmd = 'adb shell df -h'
            d = os.popen(cmd)
            f = d.read()
            # tot = f.find('3.0G')
            tot = 202
            # ava = f.find('261M')
            ava = 213
            comp_tot = f[tot:tot + 5]
            comp_ava = f[ava:ava + 5]
            self.VtotalBox.setText(comp_tot)
            self.VremainBox.setText(comp_ava)

    def data_check(self):
        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请点击连接设备")

            return no_path_warning

        try:
            device
        except NameError:
            A = no_path_warning(self)
            return
        else:
            cmd = 'adb -s ' + str(device) + ' shell "ls -a /userdata/box/data"'
            d = os.popen(cmd)
            f = d.read()
            self.textBrowser_2.setText(f)

    def path_choose(self):
        global path
        path = QFileDialog.getExistingDirectory(None,
                  "选取指定文件夹")
        self.data_path_box.setText(str(path))


    def data_choose(self):
        global path_of_data
        if hasattr(self, 'last_OpenFileName'):
            last_OpenFileName = self.last_OpenFileName
        else:
            last_OpenFileName = None

        path_of_data = QFileDialog.getOpenFileName(None,
                  "选取指定文件", last_OpenFileName, "Default Files (*.eeg;*.acc; *.emg);;All Files (*)"
                  )
        self.last_OpenFileName = os.path.dirname(path_of_data[0])
        self.data_path_box_2.setText(str(path_of_data))


    def data_choose_batch(self):
        global path_of_data_batch
        path_of_data_batch = QFileDialog.getExistingDirectory(None,
                  "选取指定文件夹")
        self.batch_translate_box.setText(str(path_of_data_batch))


    def data_sigle_translate_mat(self):
        err = data_translate_mat(path_of_data[0])
        if err is None:
            export_finish = QMessageBox.information(None, "提示", "数据转换完成，请查看原文件夹")
        else:
            export_finish = QMessageBox.information(None, "提示", err)


    def data_batch_translate_mat(self):
        def func(path:str):
            return path.endswith('.eeg') or path.endswith('.acc') or path.endswith('.sti')
        files = find_file(path_of_data_batch,func)
        for f in files:
            data_translate_mat(f)
        print(files)

        export_finish = QMessageBox.information(None, "提示", "数据转换完成，请查看原文件夹")

      
    def data_translate_edf(self):
        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请选择导出路径")

            return no_path_warning
        try:
            path_of_data
        except NameError:
            A = no_path_warning(self)
            return
        else:
            data_p = path_of_data[0]
            print(data_p[-3::])
        try:
            data_translate_edf(data_p)
        except Exception as e:
            export_finish = QMessageBox.information(None, "提示", str(e))
        else:
            export_finish = QMessageBox.information(None, "提示", "数据转换完成，请查看原文件夹")




    def data_batch_translate_edf(self):
        dir_name = path_of_data_batch
        paths = os.listdir(dir_name)
        edf_list = [os.path.join(dir_name,i) for i in paths if i.endswith('.edf') or i.endswith('.csv')]
        if len(edf_list) == len(paths):
            edf_list = [os.path.join(dir_name,i) for i in paths if i.endswith('.edf')]
            def cmp_edf(a):
                r_a = pyedflib.EdfReader(a)
                return r_a.getStartdatetime().timestamp()
            edf_list.sort(key=cmp_edf)
            base_name = os.path.basename(dir_name)
            out_name = os.path.join(dir_name,base_name)
            edf_join(edf_list, out_name)
        else:
            def func(path:str):
                if os.path.isdir(path) and is_dir_all_file(path):
                    def find_x8_data(path:str):
                        return path.endswith('.eeg') or path.endswith('.acc') or path.endswith('.qle')
                    ret = find_file(path,find_x8_data)
                    return len(ret) > 0
                else:
                    return False
                
            dirs = find_file(path_of_data_batch,func, find_dir=True ,recursion=True)
            if func(path_of_data_batch):
                dirs.append(path_of_data_batch)
            for d in dirs:
                data_translate_edf_path(d)
            print(dirs)
        export_finish = QMessageBox.information(None, "提示", "数据转换完成，请查看原文件夹")





    def data_export(self):
        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "连接设备，并选择导出路径")

            return no_path_warning
        try:
            device or path
        except NameError:
            A = no_path_warning(self)
            return
        try:
            path
        except NameError:
            A = no_path_warning(self)
            return
        else:
            # if path ==None:
            #     no_path_warning = QMessageBox.information(None, "提示", "请选择导出路径")
            #     return

            cmd = 'adb -s ' + str(device) + ' pull /userdata/box/data ' + path
            os.popen(cmd)
            cmd = 'adb -s ' + str(device) + ' pull /userdata/box/head.log ' + path
            os.popen(cmd)
            cmd = 'adb -s ' + str(device) + ' pull /userdata/box/box.log ' + path
            os.popen(cmd)
            export_finish = QMessageBox.information(None, "提示", "数据导出完成，请查看导出的文件夹")
            start_directory = path
            os.startfile(start_directory)



    def data_clear(self):

        def no_path_warning(self):

            no_path_warning = QMessageBox.information(None, "提示", "请连接设备")

            return no_path_warning
        try:
            device
        except NameError:
            A = no_path_warning(self)
            return
        else:
            cmd = f'adb -s {str(device)} shell rm -rf /userdata/box/data/*'
            os.popen(cmd)
            export_finish = QMessageBox.information(None, "提示", "数据删除完成")